### ISSUE TITLE
可否提供下您得docker镜像

### ISSUE THREAD

**Issue by w391457094** [aishang2015/Convenience#15]
请问你的docker镜像去哪里下载

**Comment by w391457094** [comment]
![image](https://user-images.githubusercontent.com/8221652/94098597-8a0fed00-fe5b-11ea-9e45-01e1e16d2e52.png)
是不是没有权限拉取镜像

**Comment by aishang2015** [comment]
看上去应该是网络原因，配置一下你的docker镜像源应该就可以了

**Comment by w391457094** [comment]
![image](https://user-images.githubusercontent.com/8221652/94636011-8a4e3380-0306-11eb-8877-63c329d55cb3.png)
连续几次都是这个问题，老大能分析下什么原因吗

**Comment by aishang2015** [comment]
应该还是网络问题，你可以把npm源换成默认的或者替换成其他的源。在src\Convience.Web\Managent下的docker文件的第五行进行配置
