### ISSUE TITLE
[Front end] Convience.Web Multi label header request

### ISSUE THREAD

**Issue by EterCyber** [aishang2015/Convenience#18]
Is it possible to add a tab to the menu bar? I feel that the layout of the title bar is empty. I only have the antd version of Vue. I have no experience in Angular. I don't know how to modify it. Can we discuss it?
![demo](https://user-images.githubusercontent.com/26731718/94636187-fdf04080-0306-11eb-8d2c-5b0099d413ab.png)

**Comment by aishang2015** [comment]
thank you for your advice ,i have already place the menu on the header bar.you can switch the side menu or the header menu by this button.in addition you can set “isSideMenu” value in the layout page to change the initiallized state.
![1](https://user-images.githubusercontent.com/16433645/94769254-31ed6380-03e4-11eb-9e73-568dbd82c1cc.PNG)

**Comment by EterCyber** [comment]
This modification is very good, but I have a new idea, which is to keep the navigation bar on the left and the header menu bar at the top. The navigation bar remains the same. The menu bar is a tab component that can switch windows and close windows, when the content page When adding, deleting or modifying (that is, the pop-up window), do not cover the header menu bar above, which helps to query and edit multiple data at the same time.
Help link:
https://ng.ant.design/components/layout/zh
https://blog.csdn.net/Gozs_cs_dn/article/details/89036670
![demo](https://user-images.githubusercontent.com/26731718/94777899-d24c8380-03f6-11eb-91c3-b486f3ef81c3.png)

**Comment by aishang2015** [comment]
one of my project have the similar effect,first you should define a RouteReuseStrategy :
```
import { RouteReuseStrategy, ActivatedRouteSnapshot, DetachedRouteHandle } from '@angular/router';
import { ComponentRef } from '@angular/core';
import { RouteStorage } from './route-storage';

export class AppReuseStrategy implements RouteReuseStrategy {

    public shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        return future.routeConfig === curr.routeConfig;
    }

    // 询问是否已经保存了当前途径的快照。
    public shouldAttach(route: ActivatedRouteSnapshot): boolean {
        if (this.shouldResetReuseStrategy(route)) {
            this.deactivateAllHandles();
            return false;
        }

        if (this.shouldIgnoreReuseStrategy(route)) {
            return false;
        }

        return RouteStorage.handles.has(this.getKey(route));
    }

    // 从存储中加载快照
    public retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle | null {
        return RouteStorage.handles.get(this.getKey(route)) || null;
    }

    public shouldDetach(route: ActivatedRouteSnapshot): boolean {
        return !this.shouldIgnoreReuseStrategy(route);
    }

    public store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle | null): void {
        if (!handle) {
            return;
        }

        RouteStorage.handles.set(this.getKey(route), handle);
    }

    private shouldResetReuseStrategy(route: ActivatedRouteSnapshot): boolean {
        let snapshot: ActivatedRouteSnapshot = route;

        while (snapshot.children && snapshot.children.length) {
            snapshot = snapshot.children[0];
        }

        return snapshot.data && snapshot.data.resetReuseStrategy;
    }

    private shouldIgnoreReuseStrategy(route: ActivatedRouteSnapshot): boolean {
        return route.data && route.data.defaultReuseStrategy;
    }

    private deactivateAllHandles(): void {
        RouteStorage.handles.forEach((handle: DetachedRouteHandle) => this.destroyComponent(handle));
        RouteStorage.handles.clear();
    }

    private destroyComponent(handle: DetachedRouteHandle): void {
        const componentRef: ComponentRef<any> = handle['componentRef'];

        if (componentRef) {
            componentRef.destroy();
        }
    }

    private getKey(route: ActivatedRouteSnapshot): string {
        return route.pathFromRoot
            .map((snapshot: ActivatedRouteSnapshot) => snapshot.routeConfig ? snapshot.routeConfig.path : '')
            .filter((path: string) => path.length > 0)
            .join('');
    }
```
this strategy supports the lazy loading.in this strategy 'RouteStorage.handles' is a static variable for store all route snapshot and restore the route .you can remove the snapshot in  this variable  when need to refresh the page. then register the strategy  in the app provider 
```
  ...
  providers: [
    { provide: NZ_I18N, useValue: zh_CN },
    InitializerService,
    { provide: APP_INITIALIZER, useFactory: initializeApp, deps: [InitializerService], multi: true },
    { provide: HTTP_INTERCEPTORS, useClass: AuthHeaderInterceptor, multi: true },
    { provide: HTTP_INTERCEPTORS, useClass: ErrorHandlerInterceptor, multi: true },
    { provide: RouteReuseStrategy, useClass: AppReuseStrategy }
  ],
  ...
```
after use this strategy all the page will be stored when the route changing .only if youdefine the route like this 
```
...
const routes: Routes = [
  {
    path: 'login', canActivate: [LoginGuard],
    loadChildren: () => import("./page/account/account.module").then(m => m.AccountModule),
    data: {
      defaultReuseStrategy: true,   // 使用默认路由策略
      resetReuseStrategy: true      // 删除所有路由快照缓存
    }
  }
]
...
```
at last the html like this 
```
        <nz-tabset [nzType]="'card'" [(nzSelectedIndex)]="tabIndex" (nzSelectedIndexChange)="indexChanged()"
            (nzSelectChange)="selectChanged()">
            <nz-tab *ngFor="let tab of tabs; let i = index" [nzTitle]="titleTemplate">
                <ng-template #titleTemplate>
                    <div>
                        <i nz-icon [nzType]="tab.icon"></i>
                        {{ tab.title }}
                        <i *ngIf="tab.canClose" nz-icon nzType="close" (click)="closeTab(i)"
                            class="ant-tabs-close-x"></i>
                    </div>
                </ng-template>
            </nz-tab>
        </nz-tabset>

```
the last of the last i use localforage to store 'tabs' data when browser closed

**Comment by EterCyber** [comment]
I tried, but the compilation failed. I modified the code in the attachment. The following is the error message:

Date: 2020-10-09T09:25:38.829Z - Hash: 3aacc3de8e0499638377
14 unchanged chunks
chunk {main} main.js, main.js.map (main) 128 kB [initial] [rendered]
Time: 1122ms
: Compiled successfully.

    ERROR in src/app/app-routing.module.ts:83:14 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    Is it missing an @NgModule annotation?

    83 export class AppRoutingModule { }
                    ~~~~~~~~~~~~~~~~
    src/app/app-routing.module.ts:83:14 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    Is it missing an @NgModule annotation?

    83 export class AppRoutingModule { }
                    ~~~~~~~~~~~~~~~~
    src/app/pages/layout/layout/layout.component.html:25:61 - error TS2339: Property 'tabIndex' does not exist on type 'LayoutComponent'.

    25           <nz-tabset [nzType]="'card'" [(nzSelectedIndex)]="tabIndex" (nzSelectedIndexChange)="indexChanged()"
                                                                   ~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:25:61 - error TS2339: Property 'tabIndex' does not exist on type 'LayoutComponent'.

    25           <nz-tabset [nzType]="'card'" [(nzSelectedIndex)]="tabIndex" (nzSelectedIndexChange)="indexChanged()"
                                                                   ~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:25:96 - error TS2339: Property 'indexChanged' does not exist on type 'LayoutComponent'.

    25           <nz-tabset [nzType]="'card'" [(nzSelectedIndex)]="tabIndex" (nzSelectedIndexChange)="indexChanged()"
                                                                                                      ~~~~~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:26:31 - error TS2339: Property 'selectChanged' does not exist on type 'LayoutComponent'.

    26             (nzSelectChange)="selectChanged()">
                                     ~~~~~~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:27:40 - error TS2339: Property 'tabs' does not exist on type 'LayoutComponent'.

    27             <nz-tab *ngFor="let tab of tabs; let i = index" [nzTitle]="titleTemplate">
                                              ~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:32:81 - error TS2339: Property 'closeTab' does not exist on type 'LayoutComponent'.

    32                         <i *ngIf="tab.canClose" nz-icon nzType="close" (click)="closeTab(i)"
                                                                                       ~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:25:11 - error NG8001: 'nz-tabset' is not a known element:
    1. If 'nz-tabset' is an Angular component, then verify that it is part of this module.
    2. If 'nz-tabset' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

    25           <nz-tabset [nzType]="'card'" [(nzSelectedIndex)]="tabIndex" (nzSelectedIndexChange)="indexChanged()"
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    26             (nzSelectChange)="selectChanged()">
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:25:22 - error NG8002: Can't bind to 'nzType' since it isn't a known property of 'nz-tabset'.
    1. If 'nz-tabset' is an Angular component and it has 'nzType' input, then verify that it is part of this module.
    2. If 'nz-tabset' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

    25           <nz-tabset [nzType]="'card'" [(nzSelectedIndex)]="tabIndex" (nzSelectedIndexChange)="indexChanged()"
                            ~~~~~~~~~~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:25:40 - error NG8002: Can't bind to 'nzSelectedIndex' since it isn't a known property of 'nz-tabset'.
    1. If 'nz-tabset' is an Angular component and it has 'nzSelectedIndex' input, then verify that it is part of this module.
    2. If 'nz-tabset' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

    25           <nz-tabset [nzType]="'card'" [(nzSelectedIndex)]="tabIndex" (nzSelectedIndexChange)="indexChanged()"
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:27:13 - error NG8001: 'nz-tab' is not a known element:
    1. If 'nz-tab' is an Angular component, then verify that it is part of this module.
    2. If 'nz-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

    27             <nz-tab *ngFor="let tab of tabs; let i = index" [nzTitle]="titleTemplate">
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.
    src/app/pages/layout/layout/layout.component.html:27:61 - error NG8002: Can't bind to 'nzTitle' since it isn't a known property of 'nz-tab'.
    1. If 'nz-tab' is an Angular component and it has 'nzTitle' input, then verify that it is part of this module.
    2. If 'nz-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

    27             <nz-tab *ngFor="let tab of tabs; let i = index" [nzTitle]="titleTemplate">
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~

      src/app/pages/layout/layout/layout.component.ts:12:16
        12   templateUrl: './layout.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component LayoutComponent.

[Managent.zip](https://github.com/aishang2015/Convenience/files/5353893/Managent.zip)

**Comment by aishang2015** [comment]
hi, I made a sample for you.you can try it.
[sample.zip](https://github.com/aishang2015/Convenience/files/5358259/sample.zip)

**Comment by EterCyber** [comment]
Hello, after running the downloaded attachment, I got the following error:

Your global Angular CLI version (10.1.0) is greater than your local
version (10.0.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

chunk {main} main.js, main.js.map (main) 2.06 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 708 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.9 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-10-10T05:57:54.315Z - Hash: 1b437f3223763ec5cb8a - Time: 19258ms

ERROR in src/app/page/layout/layout.component.ts:3:30 - error TS2307: Cannot find module 'localforage' or its corresponding type declarations.

3 import * as localforage from 'localforage';
                               ~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

`Cannot GET /`

I see another one doing better, and I hope it can help you: [yishasoft](https://yishasoft.com/admin/Home/Login)

**Comment by aishang2015** [comment]
ok,I guess you do not run "npm install" successfully.this sample is not relate to the project dont copy it to the web folder.just run it in its own folder.

**Comment by EterCyber** [comment]
Hello, after consideration, I think the Tab module should be removed, and any changes made in this issue should be restored.
