### ISSUE TITLE
数据库链接错误

### ISSUE THREAD

**Issue by yanzhen1031** [aishang2015/Convenience#37]
大佬好，这个项目没有数据库文件么？

**Comment by aishang2015** [comment]
你好，数据库初始化使用的是codefirst模式，数据库初始化代码在Program.cs的第24行
`host.InitialDataBase<SystemIdentityDbContext>(DbContextSeed.InitialApplicationDataBase);`
其中使用的EnsureCreated方法会在数据库不存在时，根据dbcontext自动进行创建
